[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../api/ ../../packages/ui/"
  command = "pnpm install && pnpm run build"
  publish = "netlify"

[build.environment]
  NODE_VERSION = "16"
