[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../api/ ../../packages/ui/"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"
  publish = "netlify"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version"
