singleQuote: true
semi: false
organizeImportsSkipDestructiveCodeActions: true
plugins:
  - prettier-plugin-tailwindcss
  - prettier-plugin-organize-imports
overrides:
  - files: 'workbox-config.cjs'
    options:
      semi: true
